

select * from T_USUARIOS;

CREATE TABLE T_USUARIOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  telefone VARCHAR(20),
  senha VARCHAR(100),
  cidade VARCHAR(50),
  estado VARCHAR(50),
  tipoUsuario ENUM('Cliente','Provedor') NOT NULL
);


CREATE TABLE T_SERVISOS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE T_provedor_servicos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  provedor_id INT NOT NULL,
  servico_id INT NOT NULL,
  FOREIGN KEY (provedor_id) REFERENCES T_USUARIOS(id) ON DELETE CASCADE,
  FOREIGN KEY (servico_id) REFERENCES T_SERVISOS(id) ON DELETE CASCADE
);
